services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "4173:80"
    depends_on:
      - backend
    container_name: frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
        weaviate:
          condition: service_healthy
    container_name: backend


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:1.30.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      LOG_LEVEL: "error"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      RAFT_BOOTSTRAP_EXPECT: 1
      CLUSTER_HOSTNAME: node1
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: True
      ENABLE_MODULES: text2vec-openai
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
      OPENAI_APIKEY: ${OPENAI_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://weaviate:8080/v1/meta"]
      interval: 5s
      timeout: 3s
      retries: 20
    container_name: weaviate

volumes:
  weaviate_data:
  product_data:
