version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - weaviate

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  weaviate:
      image: semitechnologies/weaviate:1.30.0
      ports:
        - "8080:8080"
        - "50051:50051"
      volumes:
        - weaviate_data:/var/lib/weaviate
      environment:
        QUERY_DEFAULTS_LIMIT: 25
        AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
        DEFAULT_VECTORIZER_MODULE: 'none'
        CLUSTER_HOSTNAME: 'node1'
      restart: on-failure:0

volumes:
  weaviate_data: