name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort
          # pip install pytest  # Uncomment if you add tests later

      - name: Run Black (code formatter check)
        run: |
          black --check backend/

      - name: Run Flake8 (code quality check)
        run: |
          flake8 backend/ --max-line-length=100

      - name: Run Isort (import sorting check)
        run: |
          isort --check-only backend/

      Uncomment if you add pytest tests later:
      - name: Run Tests
        run: |
          pytest backend/tests/